### PR TITLE
Cherry-pick and adapt ZOOKEEPER-2260 for getChildren pagination

### PR DESCRIPTION
**Pull request by huizhilu**
Apply PR of paginated getChildren call(https://github.com/apache/zookeeper/pull/50)

### Building
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Apache ZooKeeper 3.6.2:
[INFO]
[INFO] Apache ZooKeeper ................................... SUCCESS [  2.025 s]
[INFO] Apache ZooKeeper - Documentation ................... SUCCESS [  0.976 s]
[INFO] Apache ZooKeeper - Jute ............................ SUCCESS [  5.279 s]
[INFO] Apache ZooKeeper - Server .......................... SUCCESS [ 10.749 s]
[INFO] Apache ZooKeeper - Metrics Providers ............... SUCCESS [  0.180 s]
[INFO] Apache ZooKeeper - Prometheus.io Metrics Provider .. SUCCESS [  0.993 s]
[INFO] Apache ZooKeeper - Client .......................... SUCCESS [  0.179 s]
[INFO] Apache ZooKeeper - Recipes ......................... SUCCESS [  0.249 s]
[INFO] Apache ZooKeeper - Recipes - Election .............. SUCCESS [  0.303 s]
[INFO] Apache ZooKeeper - Recipes - Lock .................. SUCCESS [  0.298 s]
[INFO] Apache ZooKeeper - Recipes - Queue ................. SUCCESS [  0.258 s]
[INFO] Apache ZooKeeper - Assembly ........................ SUCCESS [  3.133 s]
[INFO] Apache ZooKeeper - Compatibility Tests ............. SUCCESS [  0.172 s]
[INFO] Apache ZooKeeper - Compatibility Tests - Curator ... SUCCESS [  0.243 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  25.203 s
[INFO] Finished at: 2020-11-10T18:14:05-08:00
[INFO] ------------------------------------------------------------------------
```

### Test
In module `zookeeper-server`
```
[ERROR] Errors:
[ERROR]   ZkDatabaseCorruptionTest.setUp:54 » NoSuchObject no such object in table
[ERROR]   ZkDatabaseCorruptionTest.setUp:54 » NoSuchObject no such object in table
[INFO]
[ERROR] Tests run: 3007, Failures: 0, Errors: 2, Skipped: 3
[INFO]


[INFO] Running org.apache.zookeeper.test.ZkDatabaseCorruptionTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.68 s - in org.apache.zookeeper.test.ZkDatabaseCorruptionTest
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  11.773 s
[INFO] Finished at: 2020-11-10T23:28:03-08:00
[INFO] ------------------------------------------------------------------------
```

### CODE REVIEW

**Review by junkaixue — COMMENTED** [review]
Is this native patch? Or there is something we fixed?

**Comment by huizhilu** [comment]
@dasahcc this is the original patch. Code style is formatted in the 2nd commit to pass the style check. No code logic change.

**Review by narendly — APPROVED** [review]

**Comment by narendly** [comment]
@pkuwm Curious, do we have a style.xml of some sort for ZooKeeper? I'm not seeing any style guide anywhere..

**Comment by huizhilu** [comment]
@narendly No. Zk is using the checkstyle plugin. Zk requires contributors to run unit tests by:
mvn verify spotbugs:check checkstyle:check -Pfull-build -Dsurefire-forkcount=4

And it actually checks code style. So I just adjusted the code style to pass the check style verification to make sure this pr satisfies zk check in requirements. Ref: 
https://cwiki.apache.org/confluence/display/ZOOKEEPER/HowToContribute

**Comment by narendly** [comment]
@pkuwm I see. I've had a similar experience - had to manually go in and fix style issues.

**Pull request merged**
